model:
  name: ZeroDCEPlus
  in_channels: 3
  base_channels: 32
  n_iterations: 8
  lambda_spa: 0.1
  lambda_exp: 1.0
  lambda_col: 0.5
  lambda_tv: 160.0


train:
  epochs: 100
  lr: 0.0001
  grad_clip: 0.1
  optimizer:
    name: Adam
    weight_decay: 0.0001
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 10
    min_lr: 0.000001
  log_dir: ./logs/zero_dce_plus/unpaired


data:
  name: Unpaired
  root: /home/nju-student/mkh/datasets/LLIE/ZeroDCE/train_data
  batch_size: 16
  num_workers: 4
  pin_memory: True
  height: 512
  width: 512
  val_ratio: 0.2
  seed: 42