model:
  name: EnlightenGAN
  generator:
    in_channels: 4
    base_channels: 32
  discriminator:
    in_channels: 3
    mid_channels: 64
    num_layers: 5
  patch_discriminator:
    in_channels: 3
    mid_channels: 64
    num_layers: 4
  vgg:
    in_channels: 3
    base_channels: 64
  vgg_pretrained_path: /home/nju-student/mkh/codes/LLIE/src/llie/models/vgg16.weight
  start_decay_epoch: 100
  patch_size: 32
  num_patches: 5


train:
  epochs: 200
  lr: 0.0001
  optimizer:
    name: Adam
    weight_decay: 0.0005
    betas: [0.5, 0.999]
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 10
    min_lr: 0.000001
  log_dir: ./logs/retinex_net_v2/unpaired


data:
  name: UnpairedGAN
  root: /home/nju-student/mkh/datasets/LLIE/EnlightenGAN/Train
  batch_size: 16
  num_workers: 4
  pin_memory: True
  height: 400
  width: 600
  val_ratio: 0.2
  seed: 42