model:
  name: RetinexNet
  in_channels: 4
  hidden_dim: 64
  kernel_size: 3
  num_layers: 5
  decom_epochs: 150
  relight_epochs: 100


train:
  epochs: 250
  lr: 0.001
  optimizer:
    name: Adam
    weight_decay: 0.0005
  scheduler:
    name: ReduceLROnPlateau
    factor: 0.5
    patience: 10
    min_lr: 0.000001
  log_dir: ./logs/retinex_net/lolv2_synthetic


data:
  name: LOLv2_Synthetic
  root: /home/nju-student/mkh/datasets/LLIE/LOLv2/Synthetic
  batch_size: 4
  num_workers: 4
  pin_memory: True
  height: 384
  width: 384
  val_ratio: 0.2
  seed: 42
